function [vars newData1] = importfile12(fileToRead1)

%%%%% Meant for Importin ASC files created by GageConverter program, from
%%%%% SIG files generated by GageScope. ASC file contains 12 header lines
%%%%% that must be ignored.



%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 01-Mar-2010 02:54:26

DELIMITER = '\t';
HEADERLINES = 12;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

